<a href="https://colab.research.google.com/github/sarahmilleraws/DATA_SCIENCE-Codes/blob/main/Statistics_Assignment_2_2ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [41]:
import numpy as np 
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [2]:
samples = np.random.normal(100, 15, size = 1000)
samples

array([ 75.7441873 ,  88.465137  ,  97.44619172,  86.63664425,
       121.98689347, 101.04053026,  81.43667284,  87.61340266,
        97.7441929 , 102.26905382,  73.56717056,  89.63156493,
        98.57178992,  95.40257079, 110.32182113, 103.36509971,
        89.84405743, 101.24826286, 102.25770546, 102.17824884,
        92.1171821 , 142.33710655,  85.06629181,  83.51551517,
       101.7156288 ,  77.79776233,  73.65391389, 107.20497639,
       120.44234621, 103.4169221 ,  90.79073946,  74.96096918,
       111.17693185,  93.9895039 , 102.75836942,  97.6393349 ,
       124.35345688, 103.14396979,  88.62593317,  95.76857812,
        91.77370946,  82.81593902, 133.90525473,  86.22633516,
       111.06567671,  97.60831126,  95.2217985 ,  96.0007468 ,
       115.9986621 ,  96.06217033, 113.52823582, 103.96901621,
       101.80445745,  96.4935576 ,  93.79217235,  96.34203145,
       118.86472631,  98.74627858, 105.44220873,  98.97514179,
        89.34126228, 126.85364515,  99.97132215,  96.43943056,
       120.48314576, 123.46815989, 104.5989885 ,  99.95120577,
        98.0869623 , 119.3289516 , 119.76943911, 100.34624388,
        91.17818641, 106.27665337,  80.06959634,  87.55937608,
        90.23590793,  84.32809833,  77.54046835,  87.67262678,
        94.50160476,  82.86653013,  98.69891278,  95.61742787,
       103.63010242, 108.62748979, 101.33265414, 124.30874704,
       120.24442545, 100.59107171, 104.31541299,  94.53461407,
       106.38661939,  89.30324737,  84.67709228,  88.57367053,
       100.7773552 , 123.84444912, 118.1788079 ,  82.06679025,
       116.69152434, 105.66270523, 104.15847283,  97.62334102,
        85.41241566, 107.94799696, 119.45334836,  96.17587351,
        68.82695728, 112.46168778,  93.98232661,  71.25360173,
        99.23657563,  88.91996748,  94.64379377, 103.0287638 ,
        98.9630876 , 130.19193897,  81.41921827, 108.20388703,
        86.70911813, 103.73716145, 110.40022007,  74.80590719,
       120.45966657, 102.92235995,  83.85986107,  95.27682486,
       121.60099772,  98.52236136, 101.9898919 ,  93.08075658,
       113.32956307, 112.08039403,  97.12059006, 118.5604226 ,
       130.03517663,  89.31333097, 105.92871214, 107.22115475,
       113.17515588,  85.256945  ,  90.30664964, 107.96606799,
       104.20012553, 116.86969798, 110.92519835,  99.35692745,
       125.67597126,  80.69536395, 132.30968249, 110.28215303,
        88.67810745,  95.02623035, 116.35583364, 105.27412299,
       113.93333171,  77.32377558,  88.09735179,  93.43795904,
       109.75724691, 100.22613861, 118.45217589, 116.42337812,
       101.26854502,  97.23484548,  98.41125862,  90.34751935,
       120.03283273, 113.62929461, 107.6302804 , 119.10719257,
       103.31663625,  95.1829238 , 109.33074383, 112.46860717,
        84.97045001,  85.17856439, 111.21428416,  82.08459915,
       122.02489331,  95.66756881,  95.37523307,  93.04660014,
        82.13335698, 100.44834249, 101.74336504,  84.16862482,
       114.67981255,  93.98081009, 121.12710141, 107.53859116,
        94.74310257, 114.50335915,  96.83240018, 101.79183008,
        77.73325055,  83.18326419,  91.018933  , 101.40952066,
       116.48406576, 106.56847996,  80.60634342,  90.0695679 ,
        91.07818859,  94.4279273 ,  79.0583459 , 138.35458034,
       115.64312816, 113.2891941 , 118.8775707 , 128.18219019,
        83.39348781, 128.05567276, 102.3373655 ,  84.87969116,
       107.82940976, 123.70324548, 107.70835663,  89.90117654,
       111.22337256, 123.59893736,  94.95274846,  79.75114081,
        99.91734974,  99.88775933, 106.83915054,  99.6568415 ,
       108.39089298, 116.91069938, 106.84592479, 101.16333873,
       104.69886505,  96.76525296, 108.49841185,  90.30626808,
       114.70530015,  80.44675494,  90.64942549, 113.28424309,
        96.14320665,  95.66744172,  93.15431662,  72.33037643,
       104.05160594,  74.32973952,  99.34696506, 123.31227561,
       108.83120617,  95.86865991,  95.49044934,  90.86516512,
       111.2331654 , 100.65597805, 106.24834451, 106.36334694,
       115.2270786 ,  91.496567  , 118.49831386,  92.46145675,
       126.94620248, 102.89439623, 108.31619102, 105.22176624,
       121.04685021, 138.1364572 ,  80.11640089,  74.77425446,
        80.52690443, 106.4706211 , 109.99564683, 108.96472076,
       140.24261242,  70.04270844, 122.69518077,  76.33188704,
        85.66257007,  92.3120668 , 116.99464822, 114.75242982,
        87.39150121, 102.12677577,  94.57816353, 125.24804316,
        97.5896451 ,  92.6460488 , 104.82434895, 127.00195074,
        95.27033415, 124.80219309, 119.90941188, 110.81415326,
        73.32316951, 109.83255938,  90.47855979,  92.85173444,
       118.28584952, 103.78321907, 107.56105506, 114.26057808,
        76.94165866, 105.36709234, 115.27229588, 105.02300983,
        97.14370837,  88.89647233,  94.10584999, 107.00793797,
       115.47389173,  76.58780346, 108.90969802, 105.93731994,
        95.68310545,  93.96295792, 106.14484702, 114.40722037,
       119.46288163, 101.18483391,  95.8717472 , 112.57599075,
       113.28228499,  98.63695272, 110.82955157,  97.83332087,
        70.24758363,  89.92878654,  86.89811343,  75.09071221,
       103.86867331, 100.14865685,  78.6484547 , 105.89527051,
        98.86061929, 108.62131404, 105.76437054, 105.41595094,
       103.20643241,  71.73910539, 112.69919468, 125.25803772,
       116.59791196, 100.34515058, 129.3140662 ,  97.14334017,
       136.52844885, 116.39789836,  91.9526018 ,  93.83467982,
       121.60509432,  66.20882584, 100.53996375, 106.62987594,
       109.36752963, 104.92178502, 112.20333476,  98.74044594,
        93.00803199, 101.78795942, 110.53204565, 132.21691443,
       117.90241571,  94.33379969,  81.94867878, 125.15450603,
        96.68129608, 101.33689198,  97.99409136,  73.43206139,
        95.29250508, 102.87846611,  88.4063551 ,  92.8011684 ,
       123.68311959,  88.55292293,  62.25778703, 110.76009241,
       108.2652812 ,  91.40875002, 106.54911455, 112.74195588,
        72.58684471, 105.82519209, 115.97233954, 113.86324333,
        86.23113553,  99.95190415, 104.62327981, 110.32789243,
       119.95324802,  98.03875418, 102.92673546,  87.09362351,
       110.23339268,  65.64020069,  91.64439178, 101.48636886,
       129.04528485,  84.5449006 , 127.74969286, 116.92107835,
        77.55161236, 107.54321117, 112.25656246, 108.27629243,
        72.55590367,  96.32980555, 107.61763357, 120.86575009,
        96.17904773,  91.23257008,  85.58533326, 110.45155854,
       107.02103911,  93.86767516,  97.09170697,  93.19041232,
       122.13047192, 113.59753106, 120.49952557, 108.86910618,
       110.88635757,  93.28088595, 116.05398927,  89.26976284,
       130.6157287 ,  94.01284804, 113.83752506, 107.31841396,
        95.38630423,  80.40862731,  94.07935356,  76.98950508,
        94.29638336, 107.75095482,  80.71711261,  83.06695585,
        74.27438916,  97.6270545 ,  83.27045547, 104.34573753,
        89.26629805,  92.19745319, 109.19463911, 102.42149255,
        93.01176279,  80.0935093 ,  94.40436767,  91.01231578,
       112.39006558,  94.00568515, 113.64136842,  97.7345183 ,
        95.89137357, 107.12900456,  87.54206844, 114.02416363,
       121.99798406,  87.96453897, 116.06344313,  92.75711171,
       116.59331027,  92.03801503,  90.00790646,  64.49304735,
       106.58084866,  85.75386094, 109.0824162 , 101.20080176,
       101.2741399 , 109.1705269 ,  97.61743575,  73.14436946,
        93.64098102,  93.0861131 ,  89.81751183, 116.43898499,
        84.40646993,  69.06841216,  95.75374311, 119.59545913,
        99.70939815,  94.7325048 , 112.86860333, 118.75984634,
       101.59898515,  61.23184339, 105.72542172, 108.32427842,
       115.49607813,  92.07622787, 128.70084352,  94.17017996,
        98.37203704,  94.96778443,  94.76831688, 116.46962826,
       122.26844094,  74.47297419, 101.69552847, 100.39545326,
        94.90799302,  76.17819364, 101.29639765, 106.17992912,
        64.95124109, 123.26799772,  88.33942092, 103.86413246,
       101.18536544,  94.16029077,  67.02795073, 118.55745412,
        82.26952807, 110.56817966, 114.72134677,  95.41346129,
        99.97048254, 105.08231081, 106.38923813,  89.15662905,
       121.9233185 ,  92.60750889, 106.6299963 , 108.88796008,
        95.28294904,  90.31326111, 108.3217205 , 105.75009662,
       108.11490251,  79.31289779, 121.42208367,  94.99896112,
        82.82836418,  91.8255768 , 103.83447978, 102.89153265,
        99.27197086,  90.64193136,  66.17800419,  90.66196089,
        99.38368818,  95.46639176,  78.61208417, 116.3323972 ,
       119.63896715,  77.57239882, 116.57255296,  86.2979956 ,
        77.74539449, 112.38652841,  82.33647712,  98.81705236,
       101.46434766,  90.41203785,  89.84338962,  76.14351083,
       114.17861705, 109.7523752 ,  96.45586371, 108.56086678,
       104.04236618, 128.81753484,  87.67736588, 100.7982982 ,
       105.73581553,  75.43409887,  85.30047133,  82.44028824,
       112.01773746, 135.04441428,  93.0000506 ,  88.32447221,
       112.21379712,  79.33942144, 129.0099611 ,  91.46037881,
        94.12828152, 107.97416223, 114.10595785,  86.81944535,
        85.79258257,  97.26892376, 120.55847264, 119.20616665,
       100.76258658, 112.52426673, 114.69577271, 106.3241444 ,
        89.84985624, 102.86950613, 105.49528736, 107.58107978,
       111.86962314,  93.16240923, 102.5280564 , 116.01433352,
       101.02533332, 138.23144148,  67.30778478, 113.12919361,
       104.84734209, 116.02994111,  92.73385428,  83.84146687,
       103.41488448,  97.45316603, 115.07128016, 121.20756862,
        95.20339267, 115.17694217,  84.30462183, 122.91584404,
        83.43226919,  90.50897393, 120.26627977, 110.791131  ,
        88.01918783, 111.25138664, 103.96826481, 136.04720068,
       111.39771306,  98.73231367, 102.19272093, 104.54221769,
        79.62474884,  93.60111564, 104.68953987,  90.13665303,
       117.85387389,  65.4874094 , 138.24247381,  97.25246153,
       102.103771  ,  96.01065352,  83.9529847 ,  58.06735709,
       103.78567129,  84.76721343, 125.9113704 , 103.03788959,
       115.4448399 ,  91.12390637,  96.08186954, 111.01267753,
        82.92540475, 114.58835881,  96.81340117, 102.69781645,
       112.32341393, 138.42855447,  93.8261455 , 112.79072512,
       106.26453393, 111.70600512,  80.49754749, 108.45693632,
        79.69926411, 114.82365246, 114.75357875, 128.53628182,
       129.57683438,  91.48567602, 102.4050713 ,  89.92760265,
        91.35672741,  93.96354576, 109.51473109, 102.63000933,
       107.28594244,  92.66024063,  76.35289441,  86.16672334,
       107.06076985,  87.40846305,  87.48154693,  75.78095185,
       103.95462832,  93.56885746, 101.83363212, 125.16385999,
       117.84948655,  95.78435464, 112.92360748,  94.64612575,
       106.02991364, 101.60910599,  99.06727891, 132.13135013,
        81.53307246, 136.85610621, 126.17797911, 101.1433907 ,
       113.98492582, 122.50920223, 102.53778751,  80.1374177 ,
       120.23205698,  99.19697399,  55.98391475, 112.48987113,
       100.04740771,  99.48288478, 111.47597731, 124.85316641,
       106.22088605, 102.89493948, 107.14584582, 107.55942747,
        85.36712985,  90.8486393 ,  95.922552  ,  98.9493622 ,
        87.67293087,  84.95503376,  82.48377711, 110.4754159 ,
        68.9207815 , 115.55164786,  97.38940688, 134.85128748,
       100.19618472, 109.47651436,  82.20838739,  80.35345639,
        90.09474421,  65.99617697, 104.73528742, 102.7636579 ,
        90.61475137,  98.87226769, 101.36926515,  76.72192928,
       112.11309893, 128.60067699,  66.74363131,  75.87097478,
        90.1177571 , 116.79567307, 111.12020395,  87.66201288,
        77.20296457, 102.16361966,  99.13811064,  81.76920131,
       110.64314333,  91.55846193, 109.31487555, 109.42594653,
        85.96390655,  85.73463326, 124.58125997,  99.59283251,
       110.01544356,  98.3267618 ,  89.44702228, 114.94521564,
        92.4356287 ,  98.0412579 , 106.57893448,  94.13510541,
       113.77486757, 128.68274114,  94.38466446, 105.86350004,
       117.58381922, 105.57043994, 106.08283327, 124.86035931,
       115.12024634, 136.83876807, 125.10107759,  98.72038955,
       108.84951009,  81.58326637,  74.81230572,  80.04941296,
       102.96899338,  90.26076563, 110.29233759,  93.72716364,
       114.07232416, 111.75457079,  84.44328819, 120.24573682,
       101.53243519, 107.25937954,  84.05238066, 118.77888978,
       113.03608086,  96.22562349, 108.15056316, 107.99459973,
        83.12251611, 120.02058782,  93.32244105,  84.23718927,
       108.57422438, 116.28290109, 105.50912365, 103.96976791,
       109.48282395,  86.25892602,  93.3381816 , 104.58036616,
       113.84418834, 115.31589498, 106.96467081,  87.92462771,
       131.30915993,  55.16435671, 102.32301964,  66.13920857,
        97.97892577, 117.88011414, 111.51260555, 121.56679051,
        93.53076206, 106.99151096,  85.57282172,  76.28112382,
       110.43047606, 106.02469726,  76.19090157, 106.14844064,
        89.83770358,  80.08513346, 100.87916253, 115.32250629,
       124.04643884,  91.05273042, 117.47563623, 101.64728178,
        89.14952722, 123.63633056, 111.94867571, 103.45127777,
       129.44553246,  78.47771504, 142.09329148,  92.69693379,
        87.53111165,  90.92829321, 102.43807851, 115.34509543,
       111.56302527,  77.33788081, 126.30118092, 119.54924222,
        96.89095424, 100.21612661, 112.89476429,  75.89710096,
       119.15950353,  88.16500041,  99.53238885,  99.82402167,
       112.04703974,  92.63777971, 105.57903425,  99.34867596,
       112.61837728, 131.03066618,  95.96384519,  96.06557728,
        76.07764371, 107.29574376,  69.19759245, 131.05938187,
        98.50265355, 116.2164597 , 141.18248139,  91.46524736,
        89.35198229,  84.7201204 , 116.1811495 ,  97.37015201,
       103.69829891,  97.96016418,  94.73533112,  81.99183326,
       117.67097405,  87.5020306 , 114.30082356, 118.40245935,
       108.81732026, 111.50882516,  99.45825364,  88.88387699,
        85.9791351 , 115.33256793, 111.27808158, 101.44957288,
       114.95472238,  95.460624  , 102.30900594, 100.90286231,
        94.37390004,  98.21629982, 101.42024248, 105.60394971,
        97.85416585,  92.65247542, 100.80571169,  91.72722801,
        94.86788141, 105.14039668, 119.37375147,  78.52183896,
        98.75216736,  93.99134068, 106.27316069,  77.49847018,
       104.49031473, 106.43400076, 109.93840443,  88.28959023,
       113.07979314,  73.75833535,  92.99924903, 114.02752882,
        81.16677808,  83.65776753, 114.56132803, 109.40125047,
       111.13640168,  96.71747429,  88.20130201,  97.63348972,
        90.67927705, 101.12297395,  90.47268939, 120.15009748,
       115.80492143, 100.52838553, 106.42888186, 107.37757904,
        77.87561986,  86.07764658, 107.30629283, 106.46295222,
       107.20139744,  96.91304789, 104.84614036, 120.04340067,
       107.17500355, 111.07984031,  93.34020876, 100.51351748,
       112.08191655, 102.20167737,  94.05117044, 102.07440256,
       105.67093204,  95.43623581,  95.54551879,  87.39641534,
        87.99165586,  74.67876672, 112.8008558 ,  90.78036223,
        77.89130692, 104.68007665, 110.08307533,  88.12240883,
       101.39930535,  95.72985289, 127.10943595,  90.74862001,
       110.39267512, 104.48236186, 103.23203079, 113.62023949,
       101.67815677,  93.92558607,  87.67969232, 112.50547746,
       125.67912674,  97.25206978,  93.04399075, 105.05672057,
       103.22054958,  91.98792404, 102.29450719,  64.7875786 ,
       118.07306848, 112.98956903,  90.46145739,  82.6406978 ,
       122.8391723 ,  62.31900176, 101.41405922,  98.29614943,
       120.42201177,  87.44199406, 124.17821621, 132.69552076,
       118.21686424, 108.79698253, 103.21380882,  64.7805057 ])

Compute the **mean**, **median**, and **mode**

In [3]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)

In [4]:
mean

100.9945149180072

In [5]:
median

101.28526877605259

In [6]:
mode

ModeResult(mode=array([55.16435671]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [7]:
from scipy.stats import iqr

In [8]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = iqr(samples)

In [9]:
min

55.16435670846864

In [10]:
max

142.3371065543078

In [11]:
q1

91.04428106463496

In [13]:
q3

111.23772071251936

In [14]:
iqr

20.193439647884404

Compute the **variance** and **standard deviation**

In [15]:
variance = np.var(samples)
std_dev = np.std(samples)

In [16]:
variance

224.87165148920403

In [17]:
std_dev

14.995721106009007

Compute the **skewness** and **kurtosis**

In [18]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)

In [19]:
skewness

-0.05833312017620134

In [20]:
kurtosis

-0.06065745684147528

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x =  np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
y

array([ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r =  np.corrcoef(x,y)

In [ ]:
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [ ]:
x

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [ ]:
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = scipy.stats.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = scipy.stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [37]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [38]:
tips = sns.load_dataset("tips")

In [39]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [69]:
np.var(tips)

total_bill    78.928131
tip            1.906609
size           0.900883
dtype: float64

In [26]:
np.mean(tips)

total_bill    19.785943
tip            2.998279
size           2.569672
dtype: float64

In [27]:
np.std(tips)

total_bill    8.884151
tip           1.380800
size          0.949149
dtype: float64

In [28]:
np.sqrt(np.var(tips))

total_bill    8.884151
tip           1.380800
size          0.949149
dtype: float64

In [49]:
tips["total_bill"].mode()

0    13.42
dtype: float64

In [50]:
tips["total_bill"].median()

17.795

In [51]:
tips["total_bill"].mean()

19.785942622950824

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [73]:
import scipy.stats
import numpy as np
import pandas as pd

In [79]:
tips.corr()   #Pearson Correlation

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [82]:
tips.corr(method="spearman")

            total_bill       tip      size
total_bill    1.000000  0.678968  0.604791
tip           0.678968  1.000000  0.468268
size          0.604791  0.468268  1.000000

In [83]:
tips.corr(method="kendall")

            total_bill       tip      size
total_bill    1.000000  0.517181  0.484342
tip           0.517181  1.000000  0.378185
size          0.484342  0.378185  1.000000